import { District } from './types'

export const fallbackDistricts: District[] = [
  {
    id: '0600001',
    name: 'Los Angeles Unified',
    state: 'California',
    stateAbbreviation: 'CA',
    city: 'Los Angeles',
    locale: 'urban',
    enrollment: 574570,
    graduationRate: 81.2,
    studentTeacherRatio: 23.1,
    revenuePerPupil: 16842,
    expenditurePerPupil: 15903,
  },
  {
    id: '3600001',
    name: 'New York City Public Schools',
    state: 'New York',
    stateAbbreviation: 'NY',
    city: 'New York',
    locale: 'urban',
    enrollment: 955437,
    graduationRate: 78.8,
    studentTeacherRatio: 14.5,
    revenuePerPupil: 28942,
    expenditurePerPupil: 27516,
  },
  {
    id: '1709930',
    name: 'City of Chicago SD 299',
    state: 'Illinois',
    stateAbbreviation: 'IL',
    city: 'Chicago',
    locale: 'urban',
    enrollment: 340658,
    graduationRate: 78.2,
    studentTeacherRatio: 16.3,
    revenuePerPupil: 17234,
    expenditurePerPupil: 16812,
  },
  {
    id: '4835700',
    name: 'Houston ISD',
    state: 'Texas',
    stateAbbreviation: 'TX',
    city: 'Houston',
    locale: 'urban',
    enrollment: 209772,
    graduationRate: 82.5,
    studentTeacherRatio: 17.2,
    revenuePerPupil: 11456,
    expenditurePerPupil: 10987,
  },
  {
    id: '1200390',
    name: 'Miami-Dade County Public Schools',
    state: 'Florida',
    stateAbbreviation: 'FL',
    city: 'Miami',
    locale: 'urban',
    enrollment: 350612,
    graduationRate: 84.7,
    studentTeacherRatio: 18.9,
    revenuePerPupil: 10723,
    expenditurePerPupil: 10245,
  },
  {
    id: '0408720',
    name: 'Mesa Unified District',
    state: 'Arizona',
    stateAbbreviation: 'AZ',
    city: 'Mesa',
    locale: 'suburban',
    enrollment: 63247,
    graduationRate: 86.3,
    studentTeacherRatio: 19.5,
    revenuePerPupil: 8932,
    expenditurePerPupil: 8756,
  },
  {
    id: '2502790',
    name: 'Boston Public Schools',
    state: 'Massachusetts',
    stateAbbreviation: 'MA',
    city: 'Boston',
    locale: 'urban',
    enrollment: 52565,
    graduationRate: 75.4,
    studentTeacherRatio: 12.8,
    revenuePerPupil: 25436,
    expenditurePerPupil: 24312,
  },
  {
    id: '5300300',
    name: 'Seattle Public Schools',
    state: 'Washington',
    stateAbbreviation: 'WA',
    city: 'Seattle',
    locale: 'urban',
    enrollment: 52984,
    graduationRate: 83.6,
    studentTeacherRatio: 17.1,
    revenuePerPupil: 18234,
    expenditurePerPupil: 17456,
  },
  {
    id: '0805670',
    name: 'Denver County 1',
    state: 'Colorado',
    stateAbbreviation: 'CO',
    city: 'Denver',
    locale: 'urban',
    enrollment: 92039,
    graduationRate: 72.1,
    studentTeacherRatio: 16.8,
    revenuePerPupil: 12345,
    expenditurePerPupil: 11987,
  },
  {
    id: '2700390',
    name: 'Minneapolis Public School District',
    state: 'Minnesota',
    stateAbbreviation: 'MN',
    city: 'Minneapolis',
    locale: 'urban',
    enrollment: 36478,
    graduationRate: 69.8,
    studentTeacherRatio: 15.2,
    revenuePerPupil: 19876,
    expenditurePerPupil: 18934,
  },
  {
    id: '3700600',
    name: 'Charlotte-Mecklenburg Schools',
    state: 'North Carolina',
    stateAbbreviation: 'NC',
    city: 'Charlotte',
    locale: 'urban',
    enrollment: 147854,
    graduationRate: 87.2,
    studentTeacherRatio: 16.4,
    revenuePerPupil: 10234,
    expenditurePerPupil: 9876,
  },
  {
    id: '4700450',
    name: 'Metro Nashville Public Schools',
    state: 'Tennessee',
    stateAbbreviation: 'TN',
    city: 'Nashville',
    locale: 'urban',
    enrollment: 86129,
    graduationRate: 80.5,
    studentTeacherRatio: 14.9,
    revenuePerPupil: 12678,
    expenditurePerPupil: 12234,
  },
  {
    id: '3900780',
    name: 'Columbus City School District',
    state: 'Ohio',
    stateAbbreviation: 'OH',
    city: 'Columbus',
    locale: 'urban',
    enrollment: 49734,
    graduationRate: 74.3,
    studentTeacherRatio: 15.6,
    revenuePerPupil: 14567,
    expenditurePerPupil: 13987,
  },
  {
    id: '2900300',
    name: 'St. Louis City',
    state: 'Missouri',
    stateAbbreviation: 'MO',
    city: 'St. Louis',
    locale: 'urban',
    enrollment: 20987,
    graduationRate: 68.9,
    studentTeacherRatio: 14.2,
    revenuePerPupil: 16789,
    expenditurePerPupil: 16234,
  },
  {
    id: '4100750',
    name: 'Portland SD 1J',
    state: 'Oregon',
    stateAbbreviation: 'OR',
    city: 'Portland',
    locale: 'urban',
    enrollment: 45789,
    graduationRate: 79.6,
    studentTeacherRatio: 19.3,
    revenuePerPupil: 14234,
    expenditurePerPupil: 13876,
  },
  {
    id: '2100900',
    name: 'Jefferson County',
    state: 'Kentucky',
    stateAbbreviation: 'KY',
    city: 'Louisville',
    locale: 'urban',
    enrollment: 98543,
    graduationRate: 82.1,
    studentTeacherRatio: 16.7,
    revenuePerPupil: 13456,
    expenditurePerPupil: 12987,
  },
  {
    id: '3400450',
    name: 'Newark City',
    state: 'New Jersey',
    stateAbbreviation: 'NJ',
    city: 'Newark',
    locale: 'urban',
    enrollment: 36423,
    graduationRate: 76.8,
    studentTeacherRatio: 12.3,
    revenuePerPupil: 23456,
    expenditurePerPupil: 22876,
  },
  {
    id: '1300120',
    name: 'Gwinnett County',
    state: 'Georgia',
    stateAbbreviation: 'GA',
    city: 'Suwanee',
    locale: 'suburban',
    enrollment: 179876,
    graduationRate: 88.4,
    studentTeacherRatio: 17.8,
    revenuePerPupil: 10567,
    expenditurePerPupil: 10234,
  },
  {
    id: '5101230',
    name: 'Fairfax County Public Schools',
    state: 'Virginia',
    stateAbbreviation: 'VA',
    city: 'Falls Church',
    locale: 'suburban',
    enrollment: 188543,
    graduationRate: 93.2,
    studentTeacherRatio: 15.1,
    revenuePerPupil: 17234,
    expenditurePerPupil: 16543,
  },
  {
    id: '2400090',
    name: 'Montgomery County Public Schools',
    state: 'Maryland',
    stateAbbreviation: 'MD',
    city: 'Rockville',
    locale: 'suburban',
    enrollment: 160428,
    graduationRate: 91.5,
    studentTeacherRatio: 14.7,
    revenuePerPupil: 18976,
    expenditurePerPupil: 18234,
  },
  {
    id: '1900480',
    name: 'Des Moines Independent Community SD',
    state: 'Iowa',
    stateAbbreviation: 'IA',
    city: 'Des Moines',
    locale: 'urban',
    enrollment: 33265,
    graduationRate: 77.3,
    studentTeacherRatio: 15.9,
    revenuePerPupil: 13567,
    expenditurePerPupil: 13123,
  },
  {
    id: '3100900',
    name: 'Omaha Public Schools',
    state: 'Nebraska',
    stateAbbreviation: 'NE',
    city: 'Omaha',
    locale: 'urban',
    enrollment: 52456,
    graduationRate: 83.1,
    studentTeacherRatio: 16.4,
    revenuePerPupil: 14234,
    expenditurePerPupil: 13876,
  },
  {
    id: '4000120',
    name: 'Oklahoma City Public Schools',
    state: 'Oklahoma',
    stateAbbreviation: 'OK',
    city: 'Oklahoma City',
    locale: 'urban',
    enrollment: 45678,
    graduationRate: 71.5,
    studentTeacherRatio: 17.6,
    revenuePerPupil: 9876,
    expenditurePerPupil: 9543,
  },
  {
    id: '5500600',
    name: 'Milwaukee School District',
    state: 'Wisconsin',
    stateAbbreviation: 'WI',
    city: 'Milwaukee',
    locale: 'urban',
    enrollment: 75423,
    graduationRate: 65.8,
    studentTeacherRatio: 15.3,
    revenuePerPupil: 15678,
    expenditurePerPupil: 15234,
  },
  {
    id: '2607590',
    name: 'Grand Rapids Public Schools',
    state: 'Michigan',
    stateAbbreviation: 'MI',
    city: 'Grand Rapids',
    locale: 'urban',
    enrollment: 15234,
    graduationRate: 63.2,
    studentTeacherRatio: 18.1,
    revenuePerPupil: 12345,
    expenditurePerPupil: 11987,
  },
  {
    id: '4501410',
    name: 'Greenville County Schools',
    state: 'South Carolina',
    stateAbbreviation: 'SC',
    city: 'Greenville',
    locale: 'suburban',
    enrollment: 76543,
    graduationRate: 85.7,
    studentTeacherRatio: 16.2,
    revenuePerPupil: 11234,
    expenditurePerPupil: 10876,
  },
  {
    id: '0901110',
    name: 'New Haven School District',
    state: 'Connecticut',
    stateAbbreviation: 'CT',
    city: 'New Haven',
    locale: 'urban',
    enrollment: 20123,
    graduationRate: 73.4,
    studentTeacherRatio: 12.1,
    revenuePerPupil: 22345,
    expenditurePerPupil: 21876,
  },
  {
    id: '3301050',
    name: 'Manchester School District',
    state: 'New Hampshire',
    stateAbbreviation: 'NH',
    city: 'Manchester',
    locale: 'town',
    enrollment: 13567,
    graduationRate: 79.8,
    studentTeacherRatio: 13.4,
    revenuePerPupil: 16234,
    expenditurePerPupil: 15876,
  },
  {
    id: '5000300',
    name: 'Burlington School District',
    state: 'Vermont',
    stateAbbreviation: 'VT',
    city: 'Burlington',
    locale: 'town',
    enrollment: 3876,
    graduationRate: 88.9,
    studentTeacherRatio: 11.2,
    revenuePerPupil: 21234,
    expenditurePerPupil: 20567,
  },
  {
    id: '3000900',
    name: 'Billings Public Schools',
    state: 'Montana',
    stateAbbreviation: 'MT',
    city: 'Billings',
    locale: 'town',
    enrollment: 16543,
    graduationRate: 84.3,
    studentTeacherRatio: 14.8,
    revenuePerPupil: 11567,
    expenditurePerPupil: 11234,
  },
  {
    id: '4600030',
    name: 'Sioux Falls School District',
    state: 'South Dakota',
    stateAbbreviation: 'SD',
    city: 'Sioux Falls',
    locale: 'town',
    enrollment: 25432,
    graduationRate: 87.6,
    studentTeacherRatio: 15.6,
    revenuePerPupil: 10876,
    expenditurePerPupil: 10543,
  },
  {
    id: '5600300',
    name: 'Laramie County School District 1',
    state: 'Wyoming',
    stateAbbreviation: 'WY',
    city: 'Cheyenne',
    locale: 'town',
    enrollment: 14876,
    graduationRate: 82.4,
    studentTeacherRatio: 13.7,
    revenuePerPupil: 16789,
    expenditurePerPupil: 16345,
  },
  {
    id: '1600900',
    name: 'Boise Independent District',
    state: 'Idaho',
    stateAbbreviation: 'ID',
    city: 'Boise',
    locale: 'suburban',
    enrollment: 25678,
    graduationRate: 90.1,
    studentTeacherRatio: 19.2,
    revenuePerPupil: 8567,
    expenditurePerPupil: 8234,
  },
  {
    id: '3200060',
    name: 'Clark County School District',
    state: 'Nevada',
    stateAbbreviation: 'NV',
    city: 'Las Vegas',
    locale: 'urban',
    enrollment: 326658,
    graduationRate: 82.6,
    studentTeacherRatio: 20.3,
    revenuePerPupil: 9234,
    expenditurePerPupil: 8876,
  },
  {
    id: '1500003',
    name: 'Hawaii Department of Education',
    state: 'Hawaii',
    stateAbbreviation: 'HI',
    city: 'Honolulu',
    locale: 'urban',
    enrollment: 179613,
    graduationRate: 85.8,
    studentTeacherRatio: 15.9,
    revenuePerPupil: 15678,
    expenditurePerPupil: 14987,
  },
  {
    id: '0200300',
    name: 'Anchorage School District',
    state: 'Alaska',
    stateAbbreviation: 'AK',
    city: 'Anchorage',
    locale: 'urban',
    enrollment: 46789,
    graduationRate: 79.2,
    studentTeacherRatio: 16.5,
    revenuePerPupil: 19876,
    expenditurePerPupil: 19234,
  },
  {
    id: '3500001',
    name: 'Albuquerque Public Schools',
    state: 'New Mexico',
    stateAbbreviation: 'NM',
    city: 'Albuquerque',
    locale: 'urban',
    enrollment: 85432,
    graduationRate: 71.8,
    studentTeacherRatio: 16.1,
    revenuePerPupil: 11234,
    expenditurePerPupil: 10876,
  },
  {
    id: '2000120',
    name: 'Wichita Unified School District 259',
    state: 'Kansas',
    stateAbbreviation: 'KS',
    city: 'Wichita',
    locale: 'urban',
    enrollment: 50234,
    graduationRate: 78.9,
    studentTeacherRatio: 15.8,
    revenuePerPupil: 10567,
    expenditurePerPupil: 10234,
  },
  {
    id: '0500300',
    name: 'Little Rock School District',
    state: 'Arkansas',
    stateAbbreviation: 'AR',
    city: 'Little Rock',
    locale: 'urban',
    enrollment: 23456,
    graduationRate: 75.6,
    studentTeacherRatio: 14.3,
    revenuePerPupil: 12345,
    expenditurePerPupil: 11987,
  },
  {
    id: '2200900',
    name: 'East Baton Rouge Parish School System',
    state: 'Louisiana',
    stateAbbreviation: 'LA',
    city: 'Baton Rouge',
    locale: 'urban',
    enrollment: 42567,
    graduationRate: 76.4,
    studentTeacherRatio: 15.7,
    revenuePerPupil: 12678,
    expenditurePerPupil: 12234,
  },
  {
    id: '2800090',
    name: 'Jackson Public School District',
    state: 'Mississippi',
    stateAbbreviation: 'MS',
    city: 'Jackson',
    locale: 'urban',
    enrollment: 21345,
    graduationRate: 69.5,
    studentTeacherRatio: 14.6,
    revenuePerPupil: 11567,
    expenditurePerPupil: 11234,
  },
  {
    id: '1000300',
    name: 'Red Clay Consolidated School District',
    state: 'Delaware',
    stateAbbreviation: 'DE',
    city: 'Wilmington',
    locale: 'suburban',
    enrollment: 17234,
    graduationRate: 84.5,
    studentTeacherRatio: 14.9,
    revenuePerPupil: 16234,
    expenditurePerPupil: 15876,
  },
  {
    id: '4400060',
    name: 'Providence School District',
    state: 'Rhode Island',
    stateAbbreviation: 'RI',
    city: 'Providence',
    locale: 'urban',
    enrollment: 24567,
    graduationRate: 72.3,
    studentTeacherRatio: 13.5,
    revenuePerPupil: 19876,
    expenditurePerPupil: 19234,
  },
  {
    id: '2300900',
    name: 'Portland Public Schools',
    state: 'Maine',
    stateAbbreviation: 'ME',
    city: 'Portland',
    locale: 'town',
    enrollment: 6789,
    graduationRate: 86.7,
    studentTeacherRatio: 12.3,
    revenuePerPupil: 17234,
    expenditurePerPupil: 16876,
  },
  {
    id: '5400900',
    name: 'Kanawha County Schools',
    state: 'West Virginia',
    stateAbbreviation: 'WV',
    city: 'Charleston',
    locale: 'town',
    enrollment: 25678,
    graduationRate: 87.3,
    studentTeacherRatio: 13.9,
    revenuePerPupil: 13456,
    expenditurePerPupil: 12987,
  },
  {
    id: '3800120',
    name: 'Fargo Public School District 1',
    state: 'North Dakota',
    stateAbbreviation: 'ND',
    city: 'Fargo',
    locale: 'town',
    enrollment: 11234,
    graduationRate: 89.4,
    studentTeacherRatio: 14.1,
    revenuePerPupil: 13234,
    expenditurePerPupil: 12876,
  },
  {
    id: '4900120',
    name: 'Salt Lake City School District',
    state: 'Utah',
    stateAbbreviation: 'UT',
    city: 'Salt Lake City',
    locale: 'urban',
    enrollment: 24567,
    graduationRate: 80.3,
    studentTeacherRatio: 21.3,
    revenuePerPupil: 9876,
    expenditurePerPupil: 9543,
  },
  {
    id: '4200300',
    name: 'Philadelphia City School District',
    state: 'Pennsylvania',
    stateAbbreviation: 'PA',
    city: 'Philadelphia',
    locale: 'urban',
    enrollment: 203234,
    graduationRate: 72.8,
    studentTeacherRatio: 15.4,
    revenuePerPupil: 16789,
    expenditurePerPupil: 16234,
  },
  {
    id: '1100015',
    name: 'District of Columbia Public Schools',
    state: 'Washington',
    stateAbbreviation: 'DC',
    city: 'Washington',
    locale: 'urban',
    enrollment: 49876,
    graduationRate: 73.6,
    studentTeacherRatio: 13.2,
    revenuePerPupil: 24567,
    expenditurePerPupil: 23876,
  },
]
